name: New Candidate

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
    inputs:
      candidate_username:
        description: 'GitHub username of the candidate'
        required: true
        type: string

jobs:
  run_automation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm i @octokit/core

      - name: Run automation script
        run: node .github/create-fork.js ${{ github.event.inputs.candidate_username }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
